### PR TITLE
update telegram link

### PR DESCRIPTION
**Pull request by bb2k16**

### CODE REVIEW

**Comment by LiteBit** [comment]
should keep https:// versus changing to http:// right? 

does this work for you? https://t.me/particlproject

**Comment by bb2k16** [comment]
https works for me.
http would get "re-directed" to https anyhow.

**Comment by LiteBit** [comment]
true

**Comment by allienworks** [comment]
OK, so if you get redirected to https anyway, why did you leave "http" there? O_o
Just curious.. Should I edit it?

**Pull request merged**
